import type { PageContent } from '../types'

/** Source: https://www.radiantlyalive.com/radiantly-alive-teachers (also served at /ra-movement). */
export const page: PageContent = {
  path: '/radiantly-alive-teachers',
  title: 'RA Teachers Around The World',
  description:
    'It’s been an incredible privilege to train these remarkable teachers at our Bali studio. Seek them out, join their classes, and become part of this transformative journey!',
  hero: {
    eyebrow: 'RA Movement',
    title: 'RA Teachers *Around The World*',
    lead: 'It’s been an incredible privilege to train these remarkable teachers at our Bali studio. Many are now sharing their gifts in their hometowns and across the globe, spreading the essence of yoga far and wide.',
    image: 'moveCeremonyBlessing',
    ctas: [{ label: 'Fill the form here', href: 'https://www.radiantlyalive.com/ra-teacher-directory-form' }],
  },
  blocks: [
    {
      type: 'intro',
      eyebrow: 'RA Movement',
      paragraphs: [
        'Our vision is to create a movement that empowers individuals through yoga, building a community of radiant souls. The teachers below are the heart of this vision—each one igniting positive change and inspiring others worldwide. Seek them out, join their classes, and become part of this transformative journey!',
      ],
    },
    {
      type: 'cards',
      id: 'directory',
      tone: 'paper',
      eyebrow: 'RA Teachers Directory',
      columns: 4,
      aspect: 'portrait',
      items: [
        {
          image: 'moveDirSarahChevenat',
          eyebrow: 'Australia, Sydney',
          title: 'Sarah Chevenat',
          href: '/radiantly-alive-teachers/sarah-chevenat',
          ctaLabel: 'Read More',
          links: [{ label: 'Australia', href: '/radiantly-alive-teachers/category/Australia' }],
        },
        {
          image: 'moveDirKatyGraczer',
          eyebrow: 'Australia, Sydney',
          title: 'Katy Graczer',
          href: '/radiantly-alive-teachers/katy-graczer',
          ctaLabel: 'Read More',
          links: [{ label: 'Australia', href: '/radiantly-alive-teachers/category/Australia' }],
        },
        {
          image: 'moveDirIannaNiemeijer',
          eyebrow: 'Netherlands, Amsterdam',
          title: 'Ianna Niemeijer',
          href: '/radiantly-alive-teachers/ianna-niemeijer',
          ctaLabel: 'Read More',
          links: [{ label: 'Netherlands', href: '/radiantly-alive-teachers/category/Netherlands' }],
        },
        {
          image: 'moveDirChrissiSchellhorn',
          eyebrow: 'Germany, Munich',
          title: 'Chrissi Schellhorn',
          href: '/radiantly-alive-teachers/chrissi-schellhorn',
          ctaLabel: 'Read More',
          links: [{ label: 'Germany', href: '/radiantly-alive-teachers/category/Germany' }],
        },
        {
          image: 'moveDirTuuliaTuikkuVirta',
          eyebrow: 'Finland, Tampere',
          title: 'Tuulia Tuikku Virta',
          href: '/radiantly-alive-teachers/tuulia-tuikku-virta',
          ctaLabel: 'Read More',
          links: [{ label: 'Finland', href: '/radiantly-alive-teachers/category/Finland' }],
        },
        {
          image: 'moveDirReginaJenner',
          eyebrow: 'Indonesia, Bali',
          title: 'Regina Jenner',
          href: '/radiantly-alive-teachers/regina-jenner',
          ctaLabel: 'Read More',
          links: [{ label: 'Indonesia', href: '/radiantly-alive-teachers/category/Indonesia' }],
        },
        {
          image: 'moveDirRoseDearinger',
          eyebrow: 'Australia, Adelaide',
          title: 'Rose Dearinger',
          href: '/radiantly-alive-teachers/rose-dearinger',
          ctaLabel: 'Read More',
          links: [{ label: 'Australia', href: '/radiantly-alive-teachers/category/Australia' }],
        },
        {
          image: 'moveDirLuciaTolosa',
          eyebrow: 'Indonesia, Bali',
          title: 'Lucia Tolosa',
          href: '/radiantly-alive-teachers/lucia-tolosa',
          ctaLabel: 'Read More',
          links: [{ label: 'Indonesia', href: '/radiantly-alive-teachers/category/Indonesia' }],
        },
        {
          image: 'moveDirRatihLestari',
          eyebrow: 'Indonesia, Surabaya',
          title: 'Ratih Lestari',
          href: '/radiantly-alive-teachers/ratih-lestari',
          ctaLabel: 'Read More',
          links: [{ label: 'Indonesia', href: '/radiantly-alive-teachers/category/Indonesia' }],
        },
        {
          image: 'moveDirFloreQuelin',
          eyebrow: 'France, Paris',
          title: 'Flore Quélin',
          href: '/radiantly-alive-teachers/flore-quelin',
          ctaLabel: 'Read More',
          links: [{ label: 'France', href: '/radiantly-alive-teachers/category/France' }],
        },
        {
          image: 'moveDirArielLim',
          eyebrow: 'Malaysia, Kuala Lumpur',
          title: 'Ariel Lim',
          href: '/radiantly-alive-teachers/ariel-lim',
          ctaLabel: 'Read More',
          links: [{ label: 'Malaysia', href: '/radiantly-alive-teachers/category/Malaysia' }],
        },
        {
          image: 'moveDirAlyonaKozanohina',
          eyebrow: 'Australia, Melbourne',
          title: 'Alyona Kozanohina',
          href: '/radiantly-alive-teachers/alyona-kozanohina',
          ctaLabel: 'Read More',
          links: [{ label: 'Australia', href: '/radiantly-alive-teachers/category/Australia' }],
        },
        {
          image: 'moveDirTatyanaAkman',
          eyebrow: 'Indonesia, Bali',
          title: 'Tatyana Akman',
          href: '/radiantly-alive-teachers/tatyana-akman',
          ctaLabel: 'Read More',
          links: [{ label: 'Indonesia', href: '/radiantly-alive-teachers/category/Indonesia' }],
        },
        {
          image: 'moveDirMariaClaudiaRossi',
          eyebrow: 'Peru, Lima',
          title: 'Maria Claudia Rossi',
          href: '/radiantly-alive-teachers/maria-claudia-rossi',
          ctaLabel: 'Read More',
          links: [{ label: 'Perú', href: '/radiantly-alive-teachers/category/Per%C3%BA' }],
        },
        {
          image: 'moveDirFiammaArditi',
          eyebrow: 'Italy, Rome',
          title: 'Fiamma Arditi',
          href: '/radiantly-alive-teachers/fiamma-arditi',
          ctaLabel: 'Read More',
          links: [{ label: 'Italy', href: '/radiantly-alive-teachers/category/Italy' }],
        },
        {
          image: 'moveDirAlinaSchroder',
          eyebrow: 'Germany, Frankfurt am Main',
          title: 'Alina Schröder',
          href: '/radiantly-alive-teachers/alina-schroder',
          ctaLabel: 'Read More',
          links: [{ label: 'Germany', href: '/radiantly-alive-teachers/category/Germany' }],
        },
        {
          image: 'moveDirAkhileshBodhi',
          eyebrow: 'Indonesia, Bali',
          title: 'Akhilesh Bodhi',
          href: '/radiantly-alive-teachers/akhilesh-bodhi',
          ctaLabel: 'Read More',
          links: [{ label: 'Indonesia', href: '/radiantly-alive-teachers/category/Indonesia' }],
        },
        {
          image: 'moveDirJulieKjaer',
          eyebrow: 'Denmark, Aalborg',
          title: 'Julie Kjær',
          href: '/radiantly-alive-teachers/julie-kjaer',
          ctaLabel: 'Read More',
          links: [{ label: 'Denmark', href: '/radiantly-alive-teachers/category/Denmark' }],
        },
        {
          image: 'moveDirTaniaAmorim',
          eyebrow: 'United Kingdom, London',
          title: 'Tania Amorim',
          href: '/radiantly-alive-teachers/tania-amorim',
          ctaLabel: 'Read More',
          links: [{ label: 'United Kingdom', href: '/radiantly-alive-teachers/category/United+Kingdom' }],
        },
        {
          image: 'moveDirValerieRoizen',
          eyebrow: 'France, Paris',
          title: 'Valerie Roizen',
          href: '/radiantly-alive-teachers/valerie-roizen',
          ctaLabel: 'Read More',
          links: [{ label: 'France', href: '/radiantly-alive-teachers/category/France' }],
        },
      ],
    },
    {
      type: 'lists',
      id: 'countries',
      eyebrow: 'RA Teachers Directory',
      heading: 'Search by *Country*',
      lists: [
        {
          items: [
            '[Australia](/radiantly-alive-teachers/category/Australia)',
            '[Austria](/radiantly-alive-teachers/category/Austria)',
            '[Belgium](/radiantly-alive-teachers/category/Belgium)',
            '[Canada](/radiantly-alive-teachers/category/Canada)',
            '[Chile](/radiantly-alive-teachers/category/Chile)',
            '[China](/radiantly-alive-teachers/category/China)',
            '[Czech Republic](/radiantly-alive-teachers/category/Czech%20Republic)',
            '[Denmark](/radiantly-alive-teachers/category/Denmark)',
            '[España](/radiantly-alive-teachers/category/Espa%C3%B1a)',
            '[Finland](/radiantly-alive-teachers/category/Finland)',
            '[France](/radiantly-alive-teachers/category/France)',
          ],
        },
        {
          items: [
            '[Germany](/radiantly-alive-teachers/category/Germany)',
            '[Greece](/radiantly-alive-teachers/category/Greece)',
            '[Iceland](/radiantly-alive-teachers/category/Iceland)',
            '[Indonesia](/radiantly-alive-teachers/category/Indonesia)',
            '[Ireland](/radiantly-alive-teachers/category/Ireland)',
            '[Italy](/radiantly-alive-teachers/category/Italy)',
            '[Latvia](/radiantly-alive-teachers/category/Latvia)',
            '[Luxembourg](/radiantly-alive-teachers/category/Luxembourg)',
            '[Malaysia](/radiantly-alive-teachers/category/Malaysia)',
            '[Massachusetts](/radiantly-alive-teachers/category/Massachusetts)',
            '[Namibia](/radiantly-alive-teachers/category/Namibia)',
          ],
        },
        {
          items: [
            '[Netherlands](/radiantly-alive-teachers/category/Netherlands)',
            '[Norway](/radiantly-alive-teachers/category/Norway)',
            '[Perú](/radiantly-alive-teachers/category/Per%C3%BA)',
            '[Philippines](/radiantly-alive-teachers/category/Philippines)',
            '[Singapore](/radiantly-alive-teachers/category/Singapore)',
            '[South Africa](/radiantly-alive-teachers/category/South%20Africa)',
            '[Spain](/radiantly-alive-teachers/category/Spain)',
            '[Sweden](/radiantly-alive-teachers/category/Sweden)',
            '[Switzerland](/radiantly-alive-teachers/category/Switzerland)',
            '[United Kingdom](/radiantly-alive-teachers/category/United%20Kingdom)',
            '[United States of America](/radiantly-alive-teachers/category/United%20States%20of%20America)',
          ],
        },
      ],
    },
    {
      type: 'cta',
      eyebrow: 'RA Teachers Directory',
      heading: 'If you are one of our alumni and would like to be listed in our directory,',
      image: 'moveHeroCeremony',
      ctas: [{ label: 'Fill the form here', href: 'https://www.radiantlyalive.com/ra-teacher-directory-form' }],
    },
  ],
}
