import type { PageContent } from '../types'

/** Source: https://www.radiantlyalive.com/yoga-teacher-training-2026-1 ("Start Here"; /ytt redirects here). */
export const page: PageContent = {
  path: '/yoga-teacher-training-2026-1',
  title: 'Yoga Teacher Training in Bali: 200H, Hybrid & 300H',
  description:
    'Three programs rooted in 15 years of transformational practice in Ubud. One community. A school that stays with you long after you leave. 200H Bali Immersion, 200H Hybrid and 300H Advanced, Yoga Alliance certified.',
  hero: {
    eyebrow: 'Yoga Teacher Training · Ubud, Bali · Est. 2010',
    title: 'Your teacher training. *In the place that changes everything.*',
    lead: 'Three programs rooted in 15 years of transformational practice in Ubud. One community. A school that stays with you long after you leave.',
    body: ['Many people who train here don’t come primarily to teach, they come to grow.'],
    image: 'ytt200TeachingLab',
    imagePosition: '60% 30%',
    ctas: [{ label: 'FIND YOUR PATH', href: '#proof' }],
    facts: [
      { label: 'Graduates', value: '900+' },
      { label: 'Countries', value: '80+' },
      { label: 'Yoga Alliance', value: '4.9/5' },
      { label: 'Est.', value: '2010' },
    ],
  },
  blocks: [
    {
      type: 'intro',
      align: 'center',
      paragraphs: [
        'Not sure which training is right for you? You’re in the right place. This page helps you understand your options and choose the path that fits your life.',
      ],
      ctas: [{ label: 'Compare the trainings', href: '#comparison', variant: 'link' }],
    },
    {
      type: 'split',
      eyebrow: 'BEFORE YOU CHOOSE',
      heading: 'More than a *certification course.*',
      paragraphs: [
        'Some people come to learn to teach. Others come because they feel ready for something to shift; in their practice, their direction, or how they relate to themselves. What most don’t expect is how much the training changes them either way.',
        'Whatever path you choose, you’ll leave with a Yoga Alliance qualification. But the graduates who still talk about us years later aren’t describing the curriculum. They’re describing a shift in how they see themselves.',
      ],
      note: '900+ graduates · 80+ countries · 4.9/5 Yoga Alliance · Est. 2010',
      image: 'yttStartMoreThanCertification',
      imageSide: 'left',
      shape: 'arch',
      tone: 'paper',
    },
    {
      type: 'intro',
      align: 'center',
      heading: 'Which training is *right for you?*',
      paragraphs: ['Three programs. Same transformational foundation. Different structures, different timelines, for different lives.'],
    },
    {
      type: 'cards',
      id: 'proof',
      eyebrow: 'THREE PROGRAMS',
      heading: 'Your path into teaching',
      lead: 'All three lead to a Yoga Alliance RYT-200 or RYT-500 certification. What differs is the structure, the setting, and the pace.',
      columns: 3,
      items: [
        {
          badge: 'Most Popular',
          eyebrow: '200H • YOGA ALLIANCE RYT-200',
          title: '200H Bali Immersion',
          text: 'Our flagship. A 24-day immersion in Ubud. The deepest version of this training, in the place it was built for. You arrive as a student. You leave as a teacher and something more.',
          bullets: [
            '3.5 weeks in Ubud, Bali',
            'Up to 32 students • Average 24',
            'Faculty of 5-7',
            'English & Spanish options',
            '2026 (ENG): Nov',
            '2027 (ENG): Jan • Mar • May • Aug • Nov',
            '2027 (ESP): Abril',
          ],
          note: '**Best for:** those ready to fully commit — drawn to Bali, to depth, to the most complete experience',
          href: '/200hr-yoga-teacher-training-ra-vinyasa-ubud',
          ctaLabel: 'Explore the Full Program →',
        },
        {
          eyebrow: '200H • YOGA ALLIANCE RYT-200',
          title: '200H Hybrid',
          text: 'Online modules followed by an in-person immersion in Bali or Morocco. The same curriculum, the same certification, the same faculty. Designed for those who need flexibility without compromising depth.',
          bullets: [
            'Online study + 10 days in-person immersion',
            'Locations: Bali or Morocco',
            'English & Spanish options',
            '2026 (ENG): Aug - Nov',
            '2027 (ENG): Apr-Jul | Jun-Oct',
            '2027 (ESP): Mar-Jun',
          ],
          note: '**Best for:** those with work or family commitments who want a rigorous, full training',
          href: '/200h-ytt-ra-vinyasa-hybrid',
          ctaLabel: 'Explore the Full Program →',
        },
        {
          eyebrow: '300H • YOGA ALLIANCE E-RYT 500',
          title: '300H Advanced',
          text: 'For certified teachers ready to go deeper. A 4-week advanced immersion in Ubud that refines your craft, expands your capacity, and elevates your teaching into new territory.',
          bullets: [
            '4 weeks in Ubud, Bali',
            'Requires RYT-200 + 1 yr teaching',
            'Up to 20 students • Average 15',
            'Faculty of 6-8',
            '2026: November',
            '2027: May • November',
          ],
          note: '**Best for:** certified teachers seeking E-RYT 500 status and deeper professional development',
          href: '/300hr-yoga-teacher-training-ra-vinyasa-ubud',
          ctaLabel: 'Explore the Full Program →',
        },
      ],
    },
    {
      type: 'table',
      id: 'comparison',
      eyebrow: 'QUICK COMPARISON',
      heading: 'Side by side',
      lead: 'The key differences, in one place.',
      tone: 'paper',
      columns: ['200H Bali Immersion', '200H Hybrid', '300H Advanced'],
      rows: [
        { label: 'Format', values: ['Full in-person immersion', 'Online study + in-person week', 'Full in-person immersion'] },
        { label: 'Duration', values: ['24 days in Bali', '~3 months online + 10 days in-person', '26 days in Bali'] },
        { label: 'Location', values: ['Ubud, Bali', 'Online + Bali or Morocco', 'Ubud, Bali'] },
        { label: 'Certification', values: ['Yoga Alliance RYT-200', 'Yoga Alliance RYT-200', 'Yoga Alliance E-RYT 500'] },
        { label: 'Prerequisite', values: ['None — open to all', 'None — open to all', 'RYT-200 + 1 yr teaching'] },
        { label: 'Language', values: ['English or Spanish', 'English or Spanish', 'English'] },
        { label: 'Class Size', values: ['Up to 32 students (Average 24)', 'Small group', 'Up to 20 students (Average 15)'] },
      ],
    },
    {
      type: 'split',
      eyebrow: 'WHY BALI',
      heading: 'The place does something to you *before the teaching begins.*',
      paragraphs: [
        'Ubud is not a backdrop. The rhythm of the days, the density of practice in the air, the light in the shalas, it holds the training in a way no other place can.',
        'Radiantly Alive has been here since 2010. We didn’t come to visit. We built here. Five shalas, a teaching lineage, a community rooted in this particular ground.',
      ],
      image: 'yttStartWhyBali',
      imageSide: 'right',
    },
    {
      type: 'features',
      heading: 'Six reasons this school is *different.*',
      lead: 'There are hundreds of YTTs in Bali. Here’s what sets Radiantly Alive apart, in concrete terms.',
      numbered: true,
      columns: 3,
      tone: 'paper',
      items: [
        {
          title: 'Transformation built into the structure',
          text: 'The curriculum doesn’t separate “technical” from “personal”, they’re woven together deliberately. Each day is designed to move you, not just teach you.',
        },
        {
          title: 'Faculty with real depth',
          text: 'For more than a decade, Radiantly Alive has been training teachers in Ubud. Our faculty brings together experienced educators from diverse backgrounds, creating a learning environment that combines technical expertise, personal growth, and real-world teaching experience.',
        },
        {
          title: 'Small cohorts, real mentorship',
          text: 'We believe teacher training is learned through relationship as much as curriculum. Across all our programmes, students receive direct guidance, personal feedback, and ongoing support from experienced faculty throughout the training journey.',
        },
        {
          title: '15 years, 50+ trainings, 1,000+ graduates',
          text: 'The longest-standing yoga school in Bali. Over 50 teacher trainings delivered since 2010, with a 4.9/5 rating across 150+ Yoga Alliance reviews.',
        },
        {
          title: 'Five shalas in Ubud',
          text: 'Not a hotel ballroom. Five dedicated shalas in the landscape of Ubud; open-sided, surrounded by nature, built for practice. The setting is part of the training.',
        },
        {
          title: 'A community that continues',
          text: 'Annual alumni gatherings in Barcelona, Berlin, Paris, Amsterdam. An active network across 80 countries. Graduation is not the end of the relationship.',
        },
      ],
    },
    {
      type: 'schedule',
      eyebrow: 'WHAT THE DAYS LOOK LIKE',
      heading: 'A rhythm designed to *open you up.*',
      lead: 'Days are full but not rushed. There’s a structure that balances deep learning with time to integrate, rest, and explore Ubud on your own.',
      tone: 'canvas',
      items: [
        { time: 'Morning', title: 'Opening practice', text: 'Daily asana, pranayama, or meditation. You practice before you study how to teach.' },
        {
          time: 'Daytime',
          title: 'Modules & teaching labs',
          text: 'Anatomy, philosophy, sequencing, cueing, facilitation. Mornings tend to be study; afternoons are teaching practice.',
        },
        { time: 'Evening', title: 'Integration & community', text: 'Most evenings are yours. Occasionally, we come together for an evening session.' },
        {
          time: 'Stay & Food',
          title: 'Accommodation not included — by design',
          text: 'Students arrange their own stay in Ubud, giving you personal space and flexibility. We provide recommended options at every price point.',
        },
      ],
      note: 'Full timetables are included in each programme page.',
    },
    {
      type: 'gallery',
      images: ['yttStartDailyRhythm', 'yttStartAsanaLabEspanol', 'yttStartSadhana', 'yttStartOpeningCeremony'],
    },
    {
      type: 'quote',
      tone: 'crimson',
      quote: 'I came to Bali wanting to teach. I left understanding myself.',
      name: 'Julia Rossina',
      context: '200H Bali Immersion, August 2023 · Now teaching in Rome',
      image: 'yttStartGraduateClosing',
    },
    {
      type: 'stats',
      tone: 'paper',
      heading: 'WHAT GRADUATES SAY',
      items: [
        { value: '900+', label: 'graduates worldwide' },
        { value: '4.9', label: 'Yoga Alliance rating · 150+ reviews' },
        { value: '80+', label: 'countries where RA teachers practice' },
      ],
    },
    {
      type: 'split',
      eyebrow: 'AFTER GRADUATION',
      heading: 'The training ends. *Your path doesn’t.*',
      paragraphs: [
        'Radiantly Alive graduates join a network that continues to practice, gather, and grow together. Annual alumni events in European cities. An online community spanning every timezone.',
        'Some graduates go further. They return to assist in trainings, begin teaching within the school, or step into facilitation roles over time. A few stay longer, becoming part of the team that holds the space for the next generation of students.',
        'It’s not something you sign up for. It’s what naturally unfolds when people stay connected to a place that continues to shape them.',
        'The relationships built in Ubud tend to be the thing graduates mention most, years later.',
      ],
      ctas: [{ label: 'SEE WHERE THE PATH CAN LEAD', href: '/ra-movement-academy' }],
      note: 'You don’t need to have it figured out before you reach out.',
      image: 'ytt200FacultyCeremony',
      imageSide: 'left',
    },
    {
      type: 'cards',
      eyebrow: 'WHAT WOULD YOU LIKE TO DO NEXT?',
      heading: 'Take the next step *that feels right.*',
      lead: 'There’s no rush. Wherever you are in your thinking, ready to go deeper, wanting to talk it through, or still comparing, there’s a natural next step below.',
      tone: 'paper',
      columns: 3,
      items: [
        {
          title: 'Explore the 200H Bali Immersion',
          text: 'Our signature 24-day intensive in the heart of Ubud',
          href: 'https://www.radiantlyalive.com/200hr-yoga-teacher-training-ra-vinyasa-ubud',
          ctaLabel: '→',
        },
        {
          title: 'Explore the 200H Hybrid Training',
          text: 'Study at home + Bali or Morocco immersion',
          href: 'https://www.radiantlyalive.com/200h-ytt-ra-vinyasa-hybrid',
          ctaLabel: '→',
        },
        {
          title: 'Explore the 300H Advanced Training',
          text: 'Deepen your craft after your first year of teaching',
          href: 'https://www.radiantlyalive.com/300hr-yoga-teacher-training-ra-vinyasa-ubud',
          ctaLabel: '→',
        },
      ],
    },
    {
      type: 'cta',
      heading: 'Your teacher training. *In the place that changes everything.*',
      text: 'You don’t need to have it figured out before you reach out.',
      image: 'yttStartGraduateClosing',
      ctas: [
        { label: 'FIND YOUR PATH', href: '#proof' },
        { label: 'Compare the trainings', href: '#comparison', variant: 'secondary' },
      ],
    },
  ],
  schema: {
    type: 'course',
    name: 'Yoga Teacher Training in Ubud, Bali',
    description:
      'Three programs rooted in 15 years of transformational practice in Ubud: the 200H Bali Immersion, the 200H Hybrid and the 300H Advanced, leading to Yoga Alliance RYT-200 or E-RYT 500 certification.',
  },
}
